user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    log_format json_log escape=json
        '{'
            '"source_ip":"$remote_addr",'
            '"timestamp":"$time_iso8601",'
            '"method":"$request_method",'
            '"path":"$request_uri",'
            '"status":$status,'
            '"response_size":$body_bytes_sent,'
            '"http_x_forwarded_for":"$http_x_forwarded_for",'
            '"http_user_agent":"$http_user_agent"'
        '}';

    access_log /var/log/nginx/hng-access.log json_log;

    set_real_ip_from 0.0.0.0/0;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    server {
        listen 80;

        location / {
            proxy_pass http://nextcloud;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 8080;
	server_name hng-detector.duckdns.org;

	location /api/metrics {
	    access_log off;  # don't log dashboard polling
            proxy_pass http://detector:5000;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://detector:5000;
            proxy_set_header Host $host;
        }
    }
}
